" All system-wide defaults are set in $VIMRUNTIME/archlinux.vim (usually just
" /usr/share/vim/vimfiles/archlinux.vim) and sourced by the call to :runtime
" you can find below.  If you wish to change any of those settings, you should
" do it in this file (/etc/vimrc), since archlinux.vim will be overwritten
" everytime an upgrade of the vim packages is performed.  It is recommended to
" make changes after sourcing archlinux.vim since it alters the value of the
" 'compatible' option.

" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages.
runtime! archlinux.vim

" If you prefer the old-style vim functionalty, add 'runtime! vimrc_example.vim'
" Or better yet, read /usr/share/vim/vim80/vimrc_example.vim or the vim manual
" and configure vim to your own liking!

" do not load defaults if ~/.vimrc is missing
"let skip_defaults_vim=1

syntax enable     "Enable syntax processing

" Additional colour-schemes
colorscheme badwolf
set termguicolors

" Virtual-spaces per tab (editing) and shift, tab is spaced
set tabstop=4 softtabstop=0 expandtab shiftwidth=4
" Smart-indenting at new-line, copy indents
set smartindent autoindent
inoremap jk <Esc>

" Hightlight matching parentheses, include line-numbers, last command shown
set showmatch number showcmd 
set cursorline    "Highlight current line

filetype indent on    "Load filetype-specific indent files
"Visual autocomplete for ex commands, minimise redraws
set wildmenu lazyredraw

" Ex commands to run python3 on vim, use <F9> to run
autocmd FileType python map <buffer> <F9> :w<CR>:exec '!python3' shellescape(@%, 1)<CR>
autocmd FileType python imap <buffer> <F9> <esc>:w<CR>:exec '!python3' shellescape(@%, 1)<CR>
